
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_spring_data_dio_challenge?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: dio_challenge
    password: challenge
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
